title: "Escribe tu pregunta de manera general"
labels: ["help"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Tu pregunta
      description: "Describe de manera detallada tu pregunta para que alguien te pueda apoyar"
      value: |
        No puedo arrancar el proyecto me aparece que ........
      render: bash
    validations:
      required: true
  - type: dropdown
    id: urgencia
    attributes:
      label: Urgencia
      options:
        - Alta (me bloquea mi actividad)
        - Media
        - Baja
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: ¿A qué módulo corresponde tu pregunta?
      options:
        - Tracking
        - NHO
        - Adherencia
        - Inventario
        - Performance
        - Colaboradores
        - (Otro, especifique en comentario)
    validations:
      required: true
  - type: dropdown
    id: tipo
    attributes:
      label: ¿Qué tipo de problema se te presenta?
      options:
        - Código
        - No entender algo
        - Problemas de ambiente
    validations:
      required: true
  - type: input
    id: has-id
    attributes:
      label: Comentarios
      description: Si tienes algún comentario adicional escríbelo aquí
    validations:
      required: false
