title: "Escribe tu pregunta de manera general"
labels: ["help"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Tu pregunta
      description: "Describe de manera detallada tu pregunta para que alguien te pueda apoyar"
      value: |
        No puedo arrancar el proyecto me aparece que ........
      render: bash
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: ¿A qué área corresponde tu pregunta?
      options:
        - Otra
        - Código de backend
        - Código de frontend
        - Reglas de negocio
        - Problemas de ambiente
    validations:
      required: true
  - type: input
    id: has-id
    attributes:
      label: Comentarios
      description: Si tienes algún comentario adicional escríbelo aquí
    validations:
      required: false
